@startuml

title Diagramme de classe pour DevMob

package cartomob {
    package models {
        class Building {
            - String id
            - String name
            ..Constructor..
            + Building(String name)
            ..Getters..
            + String getId()
            + String getName()
            + String getRoom(int i)
        }

        class Room {
            - String id
            - String name
            ..Constructor..
            + Room(String name)
            ..Getters..
            + Door getDoor(String id)
            + Door getDoor(Room roomId)
        }

        class RoomsHolder {}

        class Wall {}

        class Door {
            ..Constructor..
            + Door(String idRoomSrc, String idRoomDst)
        }
    }
}


RoomsHolder --"*" Room
Room "1"--"4" Wall
Building --"1" RoomsHolder
Room "2"--"*" Door
Wall --"*" Rect

@enduml